### ISSUE TITLE
building the ladybird.org site sources requires bun to run the build scripts

### ISSUE THREAD

**Issue by mrcolbyrussell** [LadybirdBrowser/ladybird.org#25] opened 2024-07-09 18:57 UTC
It should be possible to build the site using Ladybird, without needing bun.

Steps to reproduce:

1. Open Ladybird
2. Download the ladybird.org site sources from <https://github.com/LadybirdBrowser/ladybird.org>
3. Open a new tab in Ladybird and point it at the file from the ladybird.org repo that describes how to build the site
4. Follow the instructions on that page that says to use a file picker to open the source tree (or drag and drop the repo directory into Ladybird)

Expected results:

It works.

Actual results:

There is no such file with instructions as described in steps 3 and 4.  Dragging and dropping the website source code into Ladybird does nothing.  The README says use `bun install` (~~but doesn't describe how to install bun~~).

**Comment by versecafe** [comment] 2024-07-09 19:47
@mrcolbyrussell 
Either way you'd need to have bun or node installed and with node I'd have to setup instructions for NVM to make sure it's a compatible node version which is a ton of work on windows, I can go pop the install script for bun in or a link to their site since it's right at the landing page whichever you think works best

<img width="1407" alt="image" src="https://github.com/LadybirdBrowser/ladybird.org/assets/147033096/00faffce-0952-43b5-b6e3-40787c8828d7">

**Comment by ADKaster** [comment] 2024-07-09 20:07
> building the ladybird.org site sources requires bun to run the build scripts

This is true. If it were not true, we would not be able to use `astro` to make updating the site and adding blog posts easier.
Why do you expect dragging and dropping a folder into a browser to work for loading the site?

This is not a bug. What action are you hoping the maintainers will take here?

**Comment by versecafe** [comment] 2024-07-09 20:09
You need bun or node to compile astro into HTML and CSS, we use astro to reduce maintenance and code duplication, otherwise we'd have to patch things like the header nav bug on every single page, once compiled it is just plain CSS & HTML that you could drag into anything

<img width="302" alt="image" src="https://github.com/LadybirdBrowser/ladybird.org/assets/147033096/6ef462f9-4a0e-4e81-b319-2cbd8b824696">

As for steps 3/4 [route] refers to what you want the /route in the url to be you can just add a MD file and paste in the frontmatter to avoid needing to write HTML to make a new post or announcement.

**Comment by versecafe** [comment] 2024-07-09 20:13
I mean the only patch for .org would be hey if you don't have bun installed you're on macOS or linux run this 
```bash
curl -fsSL https://bun.sh/install | bash
```
if on windows run this
```ps1
powershell -c "irm bun.sh/install.ps1 | iex"
```

I kind of just left it up to google as top results for "Bun JS" or "Bun web" will be the bun.sh site

**Comment by ADKaster** [comment] 2024-07-09 20:18
The expected results are incorrect. We intentionally added a build step to the website. If that is the only feature request here, than this issue can be closed as wontfix.

**Closed by ADKaster** 2024-07-09 20:18 UTC

**Comment by versecafe** [comment] 2024-07-09 20:29
@mrcolbyrussell Andreas gave approval for the move over, and do note the ladybird.org page is not part of the SerenityOS project and is allowed to use outside code but again it only uses that during build the compiled product contains no external JS libs, the move was made to make it easier for everyone to work on and for the Ladybird devs to be able to add new posts or newsletters without needing to write a pile of HTML

<img width="610" alt="image" src="https://github.com/LadybirdBrowser/ladybird.org/assets/147033096/c8b5f894-ccdd-4b26-847d-1e5143c86fb6">

**Comment by versecafe** [comment] 2024-07-09 20:36
Ladybird (the browser) doesn't build ladybird.org from source, and it's not supposed to. Like almost the entire web there is a build step that turns a higher level system in this case Astro code and tailwind classes, into HTML and CSS, Ladybirds job is to render that output, not to compile the source Astro code. Same way google, firefox, or any other browser wouldn't compile astro.

**Comment by versecafe** [comment] 2024-07-09 21:12
No browser can build the site, you need native fs capabilities which are not part of the browser spec, as such a JS runtime like Node or Bun which extend the default JS engine with native APIs is required, A node/bun alternative built on LibJS instead of Webkit or V8 could do this if node compatible but that is currently far outside the scope of the project

**Comment by versecafe** [comment] 2024-07-09 21:27
You would have to drag and drop in the `dist/index.html` file not the base project

**Comment by versecafe** [comment] 2024-07-09 21:35
Can you please show this working in any other browser

**Comment by timschumi** [comment] 2024-07-09 22:25
> The Markdown and templates and build scripts for Aki's site are downloadable in a public repo hosted at `https://github.example/akisworld/site.git`.

This link doesn't resolve.

**Comment by timschumi** [comment] 2024-07-09 22:29
> Right. https://en.wikipedia.org/wiki/.example.

But what are we supposed to look at then? You can't just cite made-up links.

**Comment by jamierocks** [comment] 2024-07-09 22:47
I think perhaps we're losing sight of the fact, that while something else might be technically possible, using Node / Bun / X package manager isn't a mistake - it was intentional. It was a conscious decision made by the project and its contributors.

You seem to indicate a desire for vendored dependencies, perhaps that should be a separate conversation. A solution to what you are describing could be [Yarn's Zero Installs](https://yarnpkg.com/features/caching#zero-installs). I'm not advocating for their use, but there are existing solutions to the problem you described.
